User search
Benedict-Scrumberbatch/peer-recognition-backend pull request #61
Opened 2021-04-25 03:34 UTC by minhnghia2208

Changes:
/users/search?firstName=[string]&lastName=[string]     // Must specify both
/users/search?search=[string]      // search for both firstname and lastname

recognitions is similar

2021-04-27 22:22 UTC, dima618 approved these changes

2021-04-27 23:12 UTC, dima618 requested changes
I'm getting some query errors for some reason, so I'm going to request changes for now until I see why it's doing it.

2021-04-28 01:30 UTC, dima618 requested changes

2021-04-28 01:30 UTC, dima618 commented on src/users/users.service.ts
> +        .orWhere("user.lastName ilike :search", {search: '%'+search+'%'});
Can we also make this check for if firstname + lastname is similar to search and firstname + " " + lastname is similar to search?

2021-04-28 01:30 UTC, dima618 commented on src/users/users.service.ts
> +        queryBuilder.orderBy('user.firstName', 'ASC')
We should also be only looking for users with the same companyId as the JWT token

2021-04-28 01:30 UTC, dima618 commented on src/users/users.service.ts
> +        .orWhere("user.lastName ilike :search", {search: '%'+search+'%'});
Also, do we wan't to exclude the JWT user from the search results?

2021-04-28 12:08 UTC, minhnghia2208 commented on src/users/users.service.ts
> +        .orWhere("user.lastName ilike :search", {search: '%'+search+'%'});
> Also, do we wan't to exclude the JWT user from the search results?

Aside from me being lazy, I think seeing my own profile from others user perspective is a neat feature.

2021-04-28 12:09 UTC, minhnghia2208 commented on src/users/users.service.ts
> +        .orWhere("user.lastName ilike :search", {search: '%'+search+'%'});
> Can we also make this check for if firstname + lastname is similar to search and firstname + " " + lastname is similar to search?

Fix

2021-04-28 12:18 UTC, closed without merging